version: '3.8'

services:
  app:
    container_name: account-node-app
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: account-db
    depends_on:
      - db
  db:
    container_name: account-postgres-db
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
